version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: geo_tracker
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    command: ["./main", "-mode=api"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: ["./main", "-mode=worker"]
