version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: geo_tracker
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
