name: Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to aws ecr
        run: aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_IMAGE }}

      - name: Build and push ECR image
        run: |
          docker build -t ${{ env.ECR_IMAGE }} .
          docker push ${{ env.ECR_IMAGE }}

      - name: Deploy to ECS
        run: ./scripts/deploy.sh
